name: teacher_app
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firedart: ^0.9.8
  firebase_messaging: ^15.2.5
  # file_picker: ^5.0.0
  # shared_preferences: ^2.1.1
  curved_navigation_bar: ^1.0.6
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  http: ^1.3.0
  simple_animations: ^5.1.0
  table_calendar: ^3.0.9
  image_picker: ^1.0.2
  get_storage: ^2.0.3
  flutter_local_notifications: ^19.0.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
 
  uses-material-design: true
 
  assets:
    - assets/images/
    - assets/icons/
    # - assets/.env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
    - family: PermanentMarker
      fonts:
        - asset: assets/fonts/Permanent Marker/PermanentMarker-Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700