name: student_app
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  table_calendar: ^3.2.0
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  curved_navigation_bar: ^1.0.6
  smooth_page_indicator: ^1.2.1
  simple_animations: ^5.1.0
  http: ^1.3.0
  dartz: ^0.10.1
  lottie: ^3.3.1
  hidden_drawer_menu: ^3.0.1
  get_storage: ^2.1.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
    - assets/images/
 
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700